AWSTemplateFormatVersion: '2010-09-09'
Description: "CT-003 Evidence: FSI Compliant Networking (VPC & Endpoints)."

Resources:
  TenantVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Tenant-Isolated-VPC
        - Key: Compliance
          Value: FSI-Strict

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TenantVPC
      CidrBlock: 10.10.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]

  # FSI Requirement: VPC Endpoints to keep traffic off public internet
  DynamoDBEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref TenantVPC
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable