AWSTemplateFormatVersion: '2010-09-09'
Description: 'SES App Test Stack: Fixed Circular Dependency'

Parameters:
  JwtSecret:
    Type: String
    Description: "The Secret Key used in your FastAPI app to sign JWTs"
    NoEcho: true

Resources:
  # ==================================================================================
  # 1. DYNAMODB TABLES
  # ==================================================================================
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "SesApp_Users_Test"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: [{ AttributeName: "UserId", AttributeType: "S" }]
      KeySchema: [{ AttributeName: "UserId", KeyType: "HASH" }]

  ContactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "SesApp_Contacts_Test"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - { AttributeName: "ContactId", AttributeType: "S" }
        - { AttributeName: "ListId", AttributeType: "S" }
      KeySchema: [{ AttributeName: "ContactId", KeyType: "HASH" }]
      GlobalSecondaryIndexes:
        - IndexName: "ListIdIndex"
          KeySchema: [{ AttributeName: "ListId", KeyType: "HASH" }]
          Projection: { ProjectionType: "ALL" }

  ListsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "SesApp_Lists_Test"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - { AttributeName: "ListId", AttributeType: "S" }
        - { AttributeName: "UserId", AttributeType: "S" }
      KeySchema: [{ AttributeName: "ListId", KeyType: "HASH" }]
      GlobalSecondaryIndexes:
        - IndexName: "UserIndex"
          KeySchema: [{ AttributeName: "UserId", KeyType: "HASH" }]
          Projection: { ProjectionType: "ALL" }

  TemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "SesApp_Templates_Test"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - { AttributeName: "TemplateId", AttributeType: "S" }
        - { AttributeName: "UserId", AttributeType: "S" }
      KeySchema: [{ AttributeName: "TemplateId", KeyType: "HASH" }]
      GlobalSecondaryIndexes:
        - IndexName: "UserIndex"
          KeySchema: [{ AttributeName: "UserId", KeyType: "HASH" }]
          Projection: { ProjectionType: "ALL" }

  CampaignsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "SesApp_Campaigns_Test"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - { AttributeName: "CampaignId", AttributeType: "S" }
        - { AttributeName: "UserId", AttributeType: "S" }
      KeySchema: [{ AttributeName: "CampaignId", KeyType: "HASH" }]
      GlobalSecondaryIndexes:
        - IndexName: "UserIndex"
          KeySchema: [{ AttributeName: "UserId", KeyType: "HASH" }]
          Projection: { ProjectionType: "ALL" }

  # ==================================================================================
  # 2. CORE INFRASTRUCTURE
  # ==================================================================================
  UploadBucket:
    Type: AWS::S3::Bucket
    # REMOVED DependsOn to break circular dependency
    Properties:
      BucketName: !Sub "ses-app-test-upload-${AWS::AccountId}-${AWS::Region}"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: ["PUT", "POST"]
            AllowedOrigins: ["*"]
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt ProcessCsvFunction.Arn

  EmailQueue:
    Type: AWS::SQS::Queue
    Properties: 
      VisibilityTimeout: 120

  SesConfigSet:
    Type: AWS::SES::ConfigurationSet
    Properties: { Name: "SesAppTracker_Test" }

  SesEventDestination:
    Type: AWS::SES::ConfigurationSetEventDestination
    Properties:
      ConfigurationSetName: !Ref SesConfigSet
      EventDestination:
        Name: "SnsTracker"
        Enabled: true
        MatchingEventTypes: ["open", "click", "bounce", "complaint", "reject"]
        SnsDestination: { TopicARN: !Ref TrackingTopic }

  TrackingTopic:
    Type: AWS::SNS::Topic
    Properties: { TopicName: "SesEventsTopic_Test" }

  # ==================================================================================
  # 3. IAM ROLES (UPDATED TO BREAK LOOP)
  # ==================================================================================
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: [{ Effect: Allow, Principal: { Service: lambda.amazonaws.com }, Action: sts:AssumeRole }]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EmailEngineLeastPrivilege
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB Access
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !GetAtt ContactsTable.Arn
                  - !GetAtt ListsTable.Arn
                  - !GetAtt TemplatesTable.Arn
                  - !GetAtt CampaignsTable.Arn
                  - !Sub "${UsersTable.Arn}/index/*"
                  - !Sub "${ContactsTable.Arn}/index/*"
                  - !Sub "${ListsTable.Arn}/index/*"
                  - !Sub "${TemplatesTable.Arn}/index/*"
                  - !Sub "${CampaignsTable.Arn}/index/*"
              
              # S3 Access: FIXED - Removed !Ref to break circular dependency
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::ses-app-test-upload-${AWS::AccountId}-${AWS::Region}"
                  - !Sub "arn:aws:s3:::ses-app-test-upload-${AWS::AccountId}-${AWS::Region}/*"

              # SQS Access
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt EmailQueue.Arn

              # SNS Access
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref TrackingTopic

              # SES Access
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: "*"
              
              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  # ==================================================================================
  # 4. FUNCTIONS (Unchanged)
  # ==================================================================================
  AuthFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 5
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json, os, time, base64, hmac, hashlib

          def decode_jwt(token, secret):
              try:
                  parts = token.split('.')
                  if len(parts) != 3: return None
                  header_b64, payload_b64, signature_b64 = parts
                  payload_b64 += '=' * (-len(payload_b64) % 4)
                  payload = json.loads(base64.urlsafe_b64decode(payload_b64))
                  if payload.get('exp') and payload['exp'] < time.time(): return None
                  return payload
              except: return None

          def handler(event, context):
              token = event.get('headers', {}).get('authorization', '').replace('Bearer ', '')
              if not token: return {"isAuthorized": False}
              payload = decode_jwt(token, os.environ['JWT_SECRET'])
              if payload and 'email' in payload:
                  return { "isAuthorized": True, "context": { "userId": payload['email'] } }
              return {"isAuthorized": False}

  ListsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          TABLE_LISTS: !Ref ListsTable
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json, os, uuid, boto3
          from datetime import datetime
          from boto3.dynamodb.conditions import Key
          dynamodb = boto3.resource('dynamodb')
          table = dynamodb.Table(os.environ['TABLE_LISTS'])
          def handler(event, context):
              try:
                  user_id = event['requestContext']['authorizer']['lambda']['userId']
                  method = event['requestContext']['http']['method']
                  if method == 'GET':
                      response = table.query(IndexName='UserIndex', KeyConditionExpression=Key('UserId').eq(user_id))
                      return {'statusCode': 200, 'body': json.dumps(response.get('Items', []))}
                  if method == 'POST':
                      body = json.loads(event['body'])
                      item = { 'ListId': str(uuid.uuid4()), 'UserId': user_id, 'Name': body.get('name'), 'Description': body.get('description') }
                      table.put_item(Item=item)
                      return {'statusCode': 201, 'body': json.dumps(item)}
              except Exception as e: return {'statusCode': 500, 'body': str(e)}

  CampaignsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 60
      Environment:
        Variables:
          TABLE_CAMPAIGNS: !Ref CampaignsTable
          TABLE_CONTACTS: !Ref ContactsTable
          QUEUE_URL: !Ref EmailQueue
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json, os, uuid, boto3
          from boto3.dynamodb.conditions import Key
          dynamodb = boto3.resource('dynamodb')
          sqs = boto3.client('sqs')
          camp_table = dynamodb.Table(os.environ['TABLE_CAMPAIGNS'])
          def handler(event, context):
              # Simplified placeholder for brevity - your logic goes here
              return {'statusCode': 200, 'body': 'OK'}

  GetUploadUrlFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          TABLE_CAMPAIGNS: !Ref CampaignsTable
          BUCKET_NAME: !Ref UploadBucket
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json, os, boto3
          s3 = boto3.client('s3')
          def handler(event, context):
              # Simplified placeholder
              return {'statusCode': 200, 'body': 'OK'}

  ProcessCsvFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 120
      MemorySize: 256
      Environment:
        Variables:
          TABLE_CAMPAIGNS: !Ref CampaignsTable
          QUEUE_URL: !Ref EmailQueue
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json, os, boto3
          def handler(event, context):
              # Simplified placeholder
              return {'statusCode': 200, 'body': 'OK'}

  SendEmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          TABLE_USERS: !Ref UsersTable
          CONFIG_SET: !Ref SesConfigSet
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json, os, boto3
          def handler(event, context):
              # Simplified placeholder
              return {'batchItemFailures': []}

  GetBalanceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          TABLE_USERS: !Ref UsersTable
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json, os, boto3
          def handler(event, context):
              return {'statusCode': 200, 'body': '{"balance": 100}'}

  TrackerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          TABLE_CAMPAIGNS: !Ref CampaignsTable
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json, os, boto3
          def handler(event, context):
              return "OK"

  # ==================================================================================
  # 5. API GATEWAY
  # ==================================================================================
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SesApp_API_Test
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: ["*"]
        AllowHeaders: ["*"]
  
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: prod
      AutoDeploy: true

  ApiAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      Name: JwtCustomAuthorizer
      ApiId: !Ref HttpApi
      AuthorizerType: REQUEST
      AuthorizerPayloadFormatVersion: "2.0"
      AuthorizerUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthFunction.Arn}/invocations"
      IdentitySource: ["$request.header.Authorization"]
      EnableSimpleResponses: true

  # ----------------------------------------------------------------------------------
  # INTEGRATIONS
  # ----------------------------------------------------------------------------------
  IntLists:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ListsFunction.Arn
      PayloadFormatVersion: "2.0"

  IntCampaigns:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt CampaignsFunction.Arn
      PayloadFormatVersion: "2.0"

  IntUpload:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt GetUploadUrlFunction.Arn
      PayloadFormatVersion: "2.0"

  IntBalance:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt GetBalanceFunction.Arn
      PayloadFormatVersion: "2.0"

  # ----------------------------------------------------------------------------------
  # ROUTES
  # ----------------------------------------------------------------------------------
  RouteLists:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "ANY /lists"
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiAuthorizer
      Target: !Join [ "/", [ "integrations", !Ref IntLists ] ]

  RouteCampaigns:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "ANY /campaigns"
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiAuthorizer
      Target: !Join [ "/", [ "integrations", !Ref IntCampaigns ] ]

  RouteCampaignSend:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /campaigns/send"
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiAuthorizer
      Target: !Join [ "/", [ "integrations", !Ref IntCampaigns ] ]

  RouteUpload:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /upload"
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiAuthorizer
      Target: !Join [ "/", [ "integrations", !Ref IntUpload ] ]

  RouteBalance:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /balance"
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiAuthorizer
      Target: !Join [ "/", [ "integrations", !Ref IntBalance ] ]

  # ----------------------------------------------------------------------------------
  # PERMISSIONS & SUBSCRIPTIONS
  # ----------------------------------------------------------------------------------
  PermAuth:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthFunction
      Principal: apigateway.amazonaws.com

  PermLists:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ListsFunction
      Principal: apigateway.amazonaws.com

  PermCampaigns:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CampaignsFunction
      Principal: apigateway.amazonaws.com

  PermUpload:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetUploadUrlFunction
      Principal: apigateway.amazonaws.com

  PermBalance:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetBalanceFunction
      Principal: apigateway.amazonaws.com

  SqsEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt EmailQueue.Arn
      FunctionName: !Ref SendEmailFunction
      FunctionResponseTypes: ["ReportBatchItemFailures"]

  TrackerSubscription:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TrackerFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref TrackingTopic

  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt TrackerFunction.Arn
      Protocol: lambda
      TopicArn: !Ref TrackingTopic

  S3BucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProcessCsvFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"

Outputs:
  ApiUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"